version: '3.8'

services:

  flask:
    build:
      context: ./services/flask
      dockerfile: Dockerfile
    ports:
      - 5020:5000
    environment:
      - FLASK_ENV=development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
      - SERVICE_POSTGRES_SERVICE_HOST=postgres
      - POSTGRES_DB=demo_db
    depends_on:
      - postgres

  postgres:
    build:
      context: ./services/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
